# fly.toml app configuration file generated for n8n-posta on 2025-07-23T22:35:08+02:00

app = 'n8n-sneaklab'
primary_region = 'mia'

[build]
  image = 'n8nio/n8n'

[env]
  WEBHOOK_URL = "https://n8n-sneaklab.fly.dev"
  N8N_HOST = "n8n-sneaklab.fly.dev"
  N8N_PROTOCOL = "https"
  N8N_PORT = "5678"
  WHATSAPP_PHONE_NUMBER_ID = "695791806951346"
  WHATSAPP_ACCESS_TOKEN = "EAAZAH6T2spmwBPBRaWMS5NZA34EOlJPpuZCirCeS2ayYcxSGdLuJZBka4tt1QUZCRWyfmGN13xC960to3PJWeqS6tOzGPU2cbHJZCVF67YhddgsjeZAIJYDHT1zVauckXPl0MneOC6iPPZAx6n2VZCz949YZAobRZBCq43ozCrit3dNsRmS0QUDbNG1LinVfLIAuFZCx9vlzwvjQDzMLsohHDhMGQKdcFQlRj5b3vvtLRAq4pJkZD"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"
